name: Canary

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

permissions:
  contents: read

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build:
    needs: test
    if: contains(github.event.head_commit.message, '[build]')
    uses: ./.github/workflows/desktop-build.yml
    permissions:
      contents: read
