name: Canary artifacts

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

permissions: {}

jobs:
  canary-ci:
    if: "!contains(github.event.head_commit.message, 'Bump version') && !contains(github.event.head_commit.message, '[release]')"
    uses: ./.github/workflows/desktop-build.yml
    with:
      run_tests: true
    permissions:
      contents: read
